version: "3.9"
services:
  coordinator:
    build:
      context: ./Coordinator
      dockerfile: Dockerfile
      target: production
    image: coordinator:production
    networks:
      - microservices
    environment:
      CAMERA_HOST: hikrobotservice
    depends_on:
      - hikrobotservice 

  hikrobotservice:
    build:
      context: ./HikrobotCam
      dockerfile: Dockerfile
      target: production
    image: cameraservice:production
    networks:
      - microservices
    devices:
      - /dev/bus/usb:/dev/bus/usb

  dummyimagedetection:
    build:
      context: ./DummyImageDetection
      dockerfile: Dockerfile
      target: production
    image: dummyimagedetection:production
    networks:
      - microservices

  portainer-agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: always
    ports:
    - "9001:9001"  # Exposes the agent port
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
    - microservices

networks:
  microservices:
    driver: bridge
