version: "3.9"
services:
  coordinator:
    image: microservicesvt/coordinator:production
    networks:
      - microservices
    environment:
      CAMERA_HOST: hikrobotservice
    depends_on:
      - hikrobotservice 

  hikrobotservice:
    image: microservicesvt/cameraservice:production
    networks:
      - microservices
    devices:
      - /dev/bus/usb:/dev/bus/usb

  dummyimagedetection:
    image: microservicesvt/dummyimagedetection:production
    networks:
      - microservices

networks:
  microservices:
    driver: bridge