version: "3.9"
services:
  coordinator:
    build:
      context: ./Coordinator
      dockerfile: Dockerfile
      target: production
    image: coordinator
    networks:
      - microservices
    environment:
      CAMERA_HOST: hikrobotservice
    depends_on:
      - hikrobotservice 

  hikrobotservice:
    build:
      context: ./HikrobotCam
      dockerfile: Dockerfile
      target: production
    image: cameraservice
    networks:
      - microservices
    devices:
      - /dev/bus/usb:/dev/bus/usb

  dummyimagedetection:
    build:
      context: ./DummyImageDetection
      dockerfile: Dockerfile
      target: production
    image: dummyimagedetection
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
